### ISSUE TITLE
Updates from cory

### ISSUE THREAD

**Issue by keithmancuso** [familiar-studio/music-and-the-mind-of-the-world#35]
- [x] Add optional youtube link to menu next to about
- [x] Make the - into a & between two dates
- [x] Make the logos just markdown in the credits

**Comment by davefischoff** [comment]
the optional youtube link can be updated in the front matter on index.html (adding it to the config.yml didn't work- according to the Jekyll docs: "Any custom front matter that you specify will be available under  page")
